spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: file:///C:\Users\kevin\OneDrive\Escritorio\config-data
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000